# Site settings
title: Computer Scientist
email: wgriffin@fraktured.net
description: > # this means to ignore newlines until "baseurl:"
  I am a Computer Scientist in HPCVG / ACMD / ITL / NIST and a Ph.D. Candidate
  in VANGOGH / CSEE / UMBC.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fraktured.net" # the base hostname & protocol for your site
twitter_username: griffin_wes
linkedin_username: wesleygriffin
#github_username:  jekyll

# Build settings
markdown: kramdown
